"""EQL functions."""
builtins = (
    "add",
    "arrayContains",
    "arraySearch",
    "concat",
    "divide",
    "endsWith",
    "indexOf",
    "length",
    "modulo",
    "multiply",
    "number",
    "startsWith",
    "string",
    "stringContains",
    "substring",
    "subtract",
    "wildcard",
)
